version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/tony/
hooks:
  AfterInstall:
    - location: migration.sh
      timeout: 300
      runas: root
    - location: deploy.sh
      timeout: 300
      runas: ubuntu
