version: '3.4'

services:
  tony-backend.api:
    image: ${DOCKER_REGISTRY-}tonybackendapi
    build:
      context: .
      dockerfile: Tony-Backend.API/Dockerfile
    ports:
      - "3000:8081"
      - "3001:8080"
    depends_on:
      - postgresdb
    volumes:
      - ~/.aws:/app/.aws:ro
      
  postgresdb:
    hostname: postgresdb
    image: postgres:latest
    environment:
      POSTGRES_DB: tonydb
      POSTGRES_USER: tonyuser
      POSTGRES_PASSWORD: tonypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: